In [338]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [339]:
dt = pd.read_csv('covid_worldwide.csv')
dt.head()

Serial Number  Country  Total Cases Total Deaths Total Recovered   
0              1      USA  104,196,861    1,132,935     101,322,779  \
1              2    India   44,682,784      530,740      44,150,289   
2              3   France   39,524,311      164,233      39,264,546   
3              4  Germany   37,779,833      165,711      37,398,100   
4              5   Brazil   36,824,580      697,074      35,919,372   

  Active Cases     Total Test     Population  
0    1,741,147  1,159,832,679    334,805,269  
1        1,755    915,265,788  1,406,631,776  
2       95,532    271,490,188     65,584,518  
3      216,022    122,332,384     83,883,596  
4      208,134     63,776,166    215,353,593

In [340]:
dt.dtypes

Serial Number       int64
Country            object
Total Cases        object
Total Deaths       object
Total Recovered    object
Active Cases       object
Total Test         object
Population         object
dtype: object

In [341]:
dt['Total Cases'] = pd.to_numeric(dt['Total Cases'], errors='coerce', downcast='float')
dt['Total Deaths'] = pd.to_numeric(dt['Total Deaths'], errors='coerce', downcast='float')
dt['Total Recovered'] = pd.to_numeric(dt['Total Recovered'], errors='coerce', downcast='float')
dt['Active Cases'] = pd.to_numeric(dt['Active Cases'], errors='coerce', downcast='float')
dt['Total Test'] = pd.to_numeric(dt['Total Test'], errors='coerce', downcast='float')
dt['Population'] = pd.to_numeric(dt['Population'], errors='coerce', downcast='float')

In [342]:
dt.dtypes

Serial Number        int64
Country             object
Total Cases        float32
Total Deaths       float32
Total Recovered    float32
Active Cases       float32
Total Test         float32
Population         float32
dtype: object

In [343]:
dt

Serial Number           Country  Total Cases  Total Deaths   
0                1               USA          NaN           NaN  \
1                2             India          NaN           NaN   
2                3            France          NaN           NaN   
3                4           Germany          NaN           NaN   
4                5            Brazil          NaN           NaN   
..             ...               ...          ...           ...   
226            227  Diamond Princess        712.0          13.0   
227            228      Vatican City         29.0           NaN   
228            229    Western Sahara         10.0           1.0   
229            230        MS Zaandam          9.0           2.0   
230            231           Tokelau          5.0           NaN   

     Total Recovered  Active Cases  Total Test  Population  
0                NaN           NaN         NaN         NaN  
1                NaN           NaN         NaN         NaN  
2                NaN           NaN         NaN         NaN  
3                NaN           NaN         NaN         NaN  
4                NaN           NaN         NaN         NaN  
..               ...           ...         ...         ...  
226            699.0           0.0         NaN         NaN  
227             29.0           0.0         NaN       799.0  
228              9.0           0.0         NaN         NaN  
229              7.0           0.0         NaN         NaN  
230              NaN           5.0         NaN         NaN  

[231 rows x 8 columns]

In [344]:
dt.isnull().sum()

Serial Number        0
Country              0
Total Cases        225
Total Deaths       139
Total Recovered    224
Active Cases       129
Total Test         231
Population         230
dtype: int64

In [345]:
x = dt.iloc[: , 1:5].values
y = dt.iloc[:, -3:-1].values
z = dt.iloc[:, -1].values

In [346]:
print(x)

[['USA' nan nan nan]
 ['India' nan nan nan]
 ['France' nan nan nan]
 ['Germany' nan nan nan]
 ['Brazil' nan nan nan]
 ['Japan' nan nan nan]
 ['S. Korea' nan nan nan]
 ['Italy' nan nan nan]
 ['UK' nan nan nan]
 ['Russia' nan nan nan]
 ['Turkey' nan nan nan]
 ['Spain' nan nan nan]
 ['Vietnam' nan nan nan]
 ['Australia' nan nan nan]
 ['Argentina' nan nan nan]
 ['Taiwan' nan nan nan]
 ['Netherlands' nan nan nan]
 ['Iran' nan nan nan]
 ['Mexico' nan nan nan]
 ['Indonesia' nan nan nan]
 ['Poland' nan nan nan]
 ['Colombia' nan nan nan]
 ['Austria' nan nan nan]
 ['Greece' nan nan nan]
 ['Portugal' nan nan nan]
 ['Ukraine' nan nan nan]
 ['Chile' nan nan nan]
 ['Malaysia' nan nan nan]
 ['Israel' nan nan nan]
 ['DPRK' nan 74.0 nan]
 ['Thailand' nan nan nan]
 ['Belgium' nan nan nan]
 ['Czechia' nan nan nan]
 ['Canada' nan nan nan]
 ['Peru' nan nan nan]
 ['Switzerland' nan nan nan]
 ['Philippines' nan nan nan]
 ['South Africa' nan nan nan]
 ['Romania' nan nan nan]
 ['Denmark' nan nan nan]
 ['Hong K

In [347]:
print(y)

[[ nan  nan]
 [ nan  nan]
 [ nan  nan]
 [ nan  nan]
 [ nan  nan]
 [ nan  nan]
 [ nan  nan]
 [ nan  nan]
 [ nan  nan]
 [ nan  nan]
 [ nan  nan]
 [ nan  nan]
 [ nan  nan]
 [ nan  nan]
 [ nan  nan]
 [ nan  nan]
 [ nan  nan]
 [ nan  nan]
 [ nan  nan]
 [ nan  nan]
 [ nan  nan]
 [ nan  nan]
 [ nan  nan]
 [ nan  nan]
 [ nan  nan]
 [ nan  nan]
 [ nan  nan]
 [ nan  nan]
 [ nan  nan]
 [  0.  nan]
 [483.  nan]
 [ nan  nan]
 [ nan  nan]
 [ nan  nan]
 [ nan  nan]
 [ nan  nan]
 [ nan  nan]
 [ nan  nan]
 [ nan  nan]
 [ nan  nan]
 [ nan  nan]
 [ nan  nan]
 [ nan  nan]
 [673.  nan]
 [ nan  nan]
 [ nan  nan]
 [ nan  nan]
 [ nan  nan]
 [638.  nan]
 [ nan  nan]
 [ nan  nan]
 [ nan  nan]
 [ nan  nan]
 [909.  nan]
 [ nan  nan]
 [ nan  nan]
 [ nan  nan]
 [ nan  nan]
 [ nan  nan]
 [ 63.  nan]
 [535.  nan]
 [ nan  nan]
 [ nan  nan]
 [ nan  nan]
 [ nan  nan]
 [ nan  nan]
 [109.  nan]
 [ nan  nan]
 [ nan  nan]
 [ nan  nan]
 [899.  nan]
 [ 34.  nan]
 [ 18.  nan]
 [ nan  nan]
 [307.  nan]
 [ nan  nan]
 [205.  nan]

In [348]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:, 1:5])
x[:, 1:5] = imputer.transform(x[:, 1:5])

In [349]:
x

array([['USA', 252.0, 253.2608695652174, 275.7142857142857],
       ['India', 252.0, 253.2608695652174, 275.7142857142857],
       ['France', 252.0, 253.2608695652174, 275.7142857142857],
       ['Germany', 252.0, 253.2608695652174, 275.7142857142857],
       ['Brazil', 252.0, 253.2608695652174, 275.7142857142857],
       ['Japan', 252.0, 253.2608695652174, 275.7142857142857],
       ['S. Korea', 252.0, 253.2608695652174, 275.7142857142857],
       ['Italy', 252.0, 253.2608695652174, 275.7142857142857],
       ['UK', 252.0, 253.2608695652174, 275.7142857142857],
       ['Russia', 252.0, 253.2608695652174, 275.7142857142857],
       ['Turkey', 252.0, 253.2608695652174, 275.7142857142857],
       ['Spain', 252.0, 253.2608695652174, 275.7142857142857],
       ['Vietnam', 252.0, 253.2608695652174, 275.7142857142857],
       ['Australia', 252.0, 253.2608695652174, 275.7142857142857],
       ['Argentina', 252.0, 253.2608695652174, 275.7142857142857],
       ['Taiwan', 252.0, 253.260869565217

In [350]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(y[:, -3:])
y[:, -3:] = imputer.transform(y[:, -3:])

In [351]:
y

array([[179.87254, 179.87254],
       [179.87254, 179.87254],
       [179.87254, 179.87254],
       [179.87254, 179.87254],
       [179.87254, 179.87254],
       [179.87254, 179.87254],
       [179.87254, 179.87254],
       [179.87254, 179.87254],
       [179.87254, 179.87254],
       [179.87254, 179.87254],
       [179.87254, 179.87254],
       [179.87254, 179.87254],
       [179.87254, 179.87254],
       [179.87254, 179.87254],
       [179.87254, 179.87254],
       [179.87254, 179.87254],
       [179.87254, 179.87254],
       [179.87254, 179.87254],
       [179.87254, 179.87254],
       [179.87254, 179.87254],
       [179.87254, 179.87254],
       [179.87254, 179.87254],
       [179.87254, 179.87254],
       [179.87254, 179.87254],
       [179.87254, 179.87254],
       [179.87254, 179.87254],
       [179.87254, 179.87254],
       [179.87254, 179.87254],
       [179.87254, 179.87254],
       [  0.     ,   0.     ],
       [483.     , 483.     ],
       [179.87254, 179.87254],
       [

In [352]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough') 
x = np.array(ct.fit_transform(x).toarray())

In [353]:
x

array([[  0.        ,   0.        ,   0.        , ..., 252.        ,
        253.26086957, 275.71428571],
       [  0.        ,   0.        ,   0.        , ..., 252.        ,
        253.26086957, 275.71428571],
       [  0.        ,   0.        ,   0.        , ..., 252.        ,
        253.26086957, 275.71428571],
       ...,
       [  0.        ,   0.        ,   0.        , ...,  10.        ,
          1.        ,   9.        ],
       [  0.        ,   0.        ,   0.        , ...,   9.        ,
          2.        ,   7.        ],
       [  0.        ,   0.        ,   0.        , ...,   5.        ,
        253.26086957, 275.71428571]])

In [354]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
z = le.fit_transform(z)

In [355]:
z

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1], dtype=int64)